import * as path from 'path';
import * as fs from 'fs';

/**
 * JSONToPlaywrightCompiler.ts
 *
 * Converts validated JSON test specifications into executable Playwright test scripts.
 * This is the deterministic compiler that replaces AI-generated raw TypeScript code.
 */

import {
  TestSpecification,
  TestScenario,
  AnyStep,
  ActionStep,
  AssertionStep,
  GotoStep,
  FillStep,
  ClickStep,
  WaitForSelectorStep,
  WaitForResponseStep,
  SelectOptionStep,
  CheckStep,
  UploadFileStep,
  HoverStep,
  ExecuteStep,
  AssertText,
  AssertVisible,
  AssertUrl,
  AssertCount,
  AssertApiResponse,
} from './TestSpecSchema';
import { TestDataHelpers } from '../TestDataService';
import { resolveTemplate, buildDefaultContext, hasTemplateVariables, getUnresolvedVariables } from '../../utils/TemplateResolver';
import { resolveFieldSelector, resolveElementSelector, generateFallbackSelector, generateElementFallbackSelector } from '../ElementServiceQuery';
import { DiscoveryCacheService } from '../discovery/DiscoveryCacheService';
import { SelectorValidatorService } from './SelectorValidatorService';
import { SkillRegistryService } from '../skills/SkillRegistryService';
import type { InteractionStrategy, InteractionKind } from './InteractionStrategyResolver';

/**
 * Escape a string value for safe embedding in single-quoted
 * JavaScript strings within the generated test file.
 * Converts: ' → \', \ → \\\\, newlines → \\n
 */
function escapeForSingleQuote(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

/**
 * Escape a string value for safe embedding in double-quoted
 * JavaScript strings (used for console.log messages, comments).
 */
function escapeForDoubleQuote(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
}

export interface CompilerOptions {
  /** Base URL for the application */
  baseUrl: string;
  /** Ticket ID for this test run */
  ticketId: string;
  /** Optional module name for page-model-aware selector lookup */
  moduleName?: string;
  /** Whether to include video recording */
  recordVideo: boolean;
  /** Whether to include trace recording */
  recordTrace: boolean;
  /** Viewport size */
  viewport: { width: number; height: number };
  /** Login credentials (if auto-login is needed) */
  credentials?: {
    username: string;
    password: string;
    idNumber?: string;
  };
  /** Whether this is a login test (skip auto-login) */
  isLoginTest?: boolean;
  /** Timeout in milliseconds (default: 180000) */
  timeout?: number;
}

/**
 * JSON to Playwright Test Compiler
 * Converts validated JSON test specifications into executable Playwright scripts
 */
export class JSONToPlaywrightCompiler {
  private options: CompilerOptions;

  constructor(options: CompilerOptions) {
    this.options = options;
  }

  /**
   * Compile a complete test specification into a Playwright test file
   */
  compile(specification: TestSpecification): string {
    const { ticketId, feature, scenarios } = specification;
    
    // Generate unique test file content
    const testContent = scenarios.map(scenario => 
      this.compileScenario(scenario)
    ).join('\n\n');

    // Build the complete test file
    return this.buildTestFile(feature, ticketId, testContent);
  }

  /**
   * Build the complete test file with imports and configuration
   */
  private buildTestFile(feature: string, ticketId: string, testContent: string): string {
    const { baseUrl, recordVideo, recordTrace, viewport, credentials, isLoginTest, timeout } = this.options;
    const effectiveTimeout = timeout ?? 30000;
    const loginTimeout = 30000; // 30s max for login — never 3 minutes

    // Build auto-login block only when credentials are provided and this is not a login test
    const autoLoginBlock = (credentials && !isLoginTest)
      ? `
const SKIP_AUTO_LOGIN = ${Boolean(isLoginTest)};

const autoLogin = async (page: Page) => {
  try {
    if (SKIP_AUTO_LOGIN) return;

    const credentials = {
      baseUrl: '${baseUrl.replace('#/*', '')}',
      idNumber: '${credentials.idNumber || ''}',
      username: '${credentials.username}',
      password: '${credentials.password}'
    };

    const success = await performLogin(page, credentials, ${loginTimeout});
    if (!success) {
      console.log('Auto-login failed, continuing anyway...');
    }
  } catch (e) {
    console.log('Auto-login skipped or failed:', e);
  }
};`
      : '';

    return `/**
 * Auto-generated test file for ${ticketId}
 * Feature: ${feature}
 * Generated by JSONToPlaywrightCompiler
 *
 * Helpers imported from shared modules — do not redefine inline.
 */

import { test, expect, Page } from '@playwright/test';
import { performLogin } from 'D:/KMT/My class/AI/GoHybridAI/backend/tests/playwright/login-helper';
import { healedClick, waitForAngular, universalFill, kendoStabilizationDelay } from 'D:/KMT/My class/AI/GoHybridAI/backend/tests/playwright/playwright-self-healing';
import { TestDataService } from 'D:/KMT/My class/AI/GoHybridAI/backend/src/services/TestDataService';

// Wait for Kendo loading masks (inline, per-test-scenario overrides)
async function waitForLoadingMask(page: Page, timeoutMs: number = 15000): Promise<void> {
  try {
    const mask = page.locator('.k-loading-mask, .loading-overlay, .spinner-border');
    if (await mask.count() > 0) {
      await mask.first().waitFor({ state: 'hidden', timeout: timeoutMs });
    }
  } catch { /* no-op */ }
}

// Test configuration
test.use({
  baseURL: '${baseUrl}',
  video: ${recordVideo ? "'on'" : "'off'"},
  trace: ${recordTrace ? "'on'" : "'off'"},
  viewport: { width: ${viewport.width}, height: ${viewport.height} },
  actionTimeout: ${effectiveTimeout},
  navigationTimeout: ${effectiveTimeout},
});
${autoLoginBlock}

// ============================================================================
// Test Cases
// ============================================================================

${testContent}
`;
  }

  /**
   * Compile a single scenario into a test function
   */
  private compileScenario(scenario: TestScenario): string {
    const { id, name, steps, assertions, preconditions, tags, isFlaky } = scenario;

    const preconditionsComment = preconditions && preconditions.length > 0
      ? `// Pre-conditions:\n${preconditions.map(p => `//   - ${p}`).join('\n')}`
      : '';

    // --- Flakiness Auto-Tagging: inject @flaky tag if test is known to be flaky ---
    const flakyTag = isFlaky ? '@flaky (AI flagged)' : this.getFlakyTag(id);
    const allTags = tags ? [...tags] : [];
    if (flakyTag) allTags.push(flakyTag);

    const tagsComment = allTags.length > 0
      ? `// Tags: ${allTags.join(', ')}`
      : '';

    const stepsCode = steps.map(step => this.compileStep(step)).join('\n');
    const assertionsCode = assertions.map(assertion => this.compileAssertion(assertion)).join('\n');

    const loginCall = (this.options.credentials && !this.options.isLoginTest)
      ? `    // Perform auto-login first\n    await autoLogin(page);\n`
      : '';

    // Use test.fixme() for flaky tests so they run but don't fail the suite
    const testDecl = flakyTag
      ? `  test.fixme('Flaky test — auto-tagged by GoHybrid AI', { run: true });\n  test('Execute test scenario (flaky)', async ({ page }) => {`
      : `  test('Execute test scenario', async ({ page }) => {`;

    return `
test.describe('${id}: ${name}', () => {
${testDecl}
    ${preconditionsComment}
    ${tagsComment}

    // Unique test data for this run (prevents duplicate record failures)
    const testData = new TestDataService(page);

    console.log('Starting scenario: ${name}');
${loginCall}
    // Execute steps
    ${stepsCode}

    // Verify assertions
    ${assertionsCode}

    // Cleanup: delete any records created during this test
    try { await testData.cleanup(); } catch { /* cleanup best-effort */ }

    console.log('Scenario completed: ${name}');
  });
});`;
  }

  /**
   * Check if a test case is known to be flaky and return the tag.
   * Reads the flakiness store directly (no singleton needed).
   */
  private getFlakyTag(testCaseId: string): string | null {
    try {
      const storePath = path.join(
        process.env.LOCAL_STORAGE_PATH || path.join(__dirname, '../../../local_storage'),
        'flakiness-tracker.json'
      );
      if (!fs.existsSync(storePath)) return null;

      const store = JSON.parse(fs.readFileSync(storePath, 'utf-8'));
      const records = store[testCaseId];
      if (!records || records.length < 5) return null; // Need minimum data

      const recent = records.slice(-10);
      const failCount = recent.filter((r: any) => r.status === 'FAIL').length;
      const failureRate = failCount / recent.length;

      // Mark as flaky if >30% failure rate in recent executions
      if (failureRate > 0.3 && failureRate < 0.95) {
        return `@flaky (${Math.round(failureRate * 100)}% fail rate)`;
      }
    } catch {
      // Ignore read errors — test is not flaky
    }
    return null;
  }

  /**
   * Compile a single action step into Playwright code
   */
  private compileStep(step: AnyStep): string {
    switch (step.type) {
      case 'goto':
        return this.compileGotoStep(step);
      case 'fill':
        return this.compileFillStep(step);
      case 'click':
        return this.compileClickStep(step);
      case 'waitForSelector':
        return this.compileWaitForSelectorStep(step);
      case 'waitForResponse':
        return this.compileWaitForResponseStep(step);
      case 'selectOption':
        return this.compileSelectOptionStep(step);
      case 'check':
        return this.compileCheckStep(step);
      case 'uploadFile':
        return this.compileUploadFileStep(step);
      case 'hover':
        return this.compileHoverStep(step);
      case 'execute':
        return this.compileExecuteStep(step);
      case 'assertText':
        return this.compileAssertText(step);
      case 'assertVisible':
        return this.compileAssertVisible(step);
      case 'assertUrl':
        return this.compileAssertUrl(step);
      case 'assertCount':
        return this.compileassertCount(step);
      case 'assertApiResponse':
        return this.compileAssertApiResponse(step);
      default:
        return `// Unknown step type: ${(step as any).type}`;
    }
  }

  private compileGotoStep(step: GotoStep): string {
    // ROOT CAUSE FIX #1: 'commit' returns immediately for hash-only navigation.
    // 'domcontentloaded' ensures DOM is ready before checking selectors.
    const waitUntil = 'domcontentloaded'; // Better for Angular SPA hash navigation

    // Resolve any template variables in the URL
    let resolvedUrl = resolveTemplate(step.url, buildDefaultContext({ baseUrl: this.options.baseUrl }));
    const unresolved = getUnresolvedVariables(step.url);

    // STRIP ABSOLUTE URLs: If AI generated a full URL, strip the origin and keep only path+hash
    try {
      const urlObj = new URL(resolvedUrl);
      // If the URL has an origin different from baseURL (or is absolute), strip it
      const baseUrlObj = new URL(this.options.baseUrl);
      if (urlObj.origin !== baseUrlObj.origin || resolvedUrl.startsWith('http')) {
        const relativePath = urlObj.pathname + urlObj.search + urlObj.hash;
        console.warn(`[JSONToPlaywrightCompiler] ⚠️ Detected hardcoded URL, stripping origin: ${resolvedUrl} → ${relativePath}`);
        resolvedUrl = relativePath;
      }
    } catch {
      // Not a valid URL, keep as-is (it's probably already a relative path)
    }

    if (unresolved.length > 0) {
      console.warn(`[JSONToPlaywrightCompiler] Unresolved variables in goto step: ${unresolved.join(', ')}. Using baseUrl fallback.`);
    }

    let finalUrl = unresolved.length > 0 ? this.options.baseUrl : resolvedUrl;

    // GlobalHR / Angular hash routing normalization:
    // - baseUrl often includes a path segment like "/ook"
    // - a goto URL like "/#/app.department" would drop "/ook" if passed to page.goto()
    // Normalize common forms into a stable absolute URL: `${baseUrl}#/...`
    //
    // Supported inputs:
    // - "/#/app.department" -> "https://host/ook#/app.department"
    // - "#/app.department"  -> "https://host/ook#/app.department"
    // - "/ook#/app.department" stays as-is
    if (finalUrl.startsWith('/#/')) {
      finalUrl = `${this.options.baseUrl}${finalUrl.slice(1)}`; // remove leading "/"
    } else if (finalUrl.startsWith('#/')) {
      finalUrl = `${this.options.baseUrl}${finalUrl}`;
    }

    // Warn if hardcoded URL is still detected in the original step
    if (step.url.startsWith('http://') || step.url.startsWith('https://')) {
      console.warn(`[JSONToPlaywrightCompiler] ⚠️ WARNING: Test step contains hardcoded absolute URL. Use relative paths like '/#/app.designation' instead.`);
    }

    return `
    // Navigate to ${finalUrl}
    console.log('Navigating to: ${finalUrl}');
    await page.goto('${finalUrl}', { waitUntil: 'domcontentloaded', timeout: 30000 });
    // Wait for Angular router to process the hash and render the lazy-loaded component
    await page.waitForTimeout(5000);
    await waitForAngular(page);
    // If we're still on login page, try hash navigation instead
    const currentUrl = page.url();
    if (currentUrl.includes('/login')) {
      console.log('[Nav] Still on login page, retrying with hash navigation...');
      await page.evaluate((hash) => {
        window.location.hash = hash.replace(/.*?(#.*)/, '$1');
      }, '${finalUrl}');
      await page.waitForTimeout(3000);
      await waitForAngular(page);
    }`;
  }

  private compileFillStep(step: FillStep): string {
    // PRIORITY 1: Look up real selector from discovery cache
    let selector = step.selectorHint;
    let locatorSource = 'step.selectorHint';
    if (!selector && this.options.moduleName) {
      const discovered = DiscoveryCacheService.lookupElementDefinition(step.field, this.options.moduleName);
      if (discovered) {
        selector = discovered.selector;
        locatorSource = 'DiscoveryCache';
        // Inject framework/strategy from discovery if not already set
        (step as any).framework = (step as any).framework || discovered.framework;
        (step as any).strategyKind = (step as any).strategyKind || discovered.strategyKind;
      }
    }

    // PRIORITY 1.5: Look up from locator knowledge base (successful test runs)
    if (!selector && this.options.moduleName) {
      const knownLocator = SkillRegistryService.findBestLocator(step.field, 'fill');
      if (knownLocator && knownLocator.confidence >= 0.7) {
        selector = knownLocator.selector;
        locatorSource = `SkillRegistry(confidence=${(knownLocator.confidence * 100).toFixed(0)}%)`;
        (step as any).framework = (step as any).framework || knownLocator.framework;
        (step as any).strategyKind = (step as any).strategyKind || knownLocator.strategyKind;
      }
    }

    // PRIORITY 2: Fallback to hardcoded field map
    if (!selector) {
      // Map common field names to actual GlobalHR selectors
      const fieldSelectorMap: Record<string, string> = {
        'idnumber': 'input[name="idnumber"], #idnumber',
        'username': 'input[name="username"], #username',
        'password': 'input[name="password"], #password',
        'title': 'input[name="title"], #title, textarea[name="title"]',
        'category': 'input[name="category"], #category, .k-dropdown',
        'description': 'textarea[name="description"], #description, input[name="description"]',
        'labelName': 'input[name="name"], #name, input[name="labelName"]',
      };
      selector = fieldSelectorMap[step.field.toLowerCase()] || `input[name="${step.field}"], #${step.field}, [placeholder*="${step.field}" i]`;
    }

    // Resolve template variables in value.
    // buildDefaultContext() includes: {{timestamp}}, {{unique_id}}, {{random}}, {{base_url}}, etc.
    const rawValue = String(step.value);
    const resolvedValue = resolveTemplate(rawValue, buildDefaultContext());
    // Check AFTER resolution — only truly unresolved variables (not in context) remain
    const unresolved = getUnresolvedVariables(resolvedValue);

    if (unresolved.length > 0) {
      console.warn(`[JSONToPlaywrightCompiler] Unresolved variables in fill value for ${step.field}: ${unresolved.join(', ')}. Using empty string.`);
    }

    // UNIQUE DATA: Replace hardcoded string values with TestDataHelpers calls.
    // If the value is a plain string (no template variables), generate unique data.
    // This prevents duplicate record failures from hardcoded values like "HR", "Human Resources".
    let finalValue: string;
    let isUniqueValue = false;
    if (unresolved.length > 0) {
      finalValue = '';
    } else if (rawValue === resolvedValue && resolvedValue.length > 0 && !rawValue.includes('${')) {
      // Hardcoded string — replace with unique value
      const fieldLower = step.field.toLowerCase();
      if (fieldLower.includes('shortcode') || fieldLower.includes('short_code') || fieldLower.includes('code')) {
        // Short code: max 5 chars, use uniqueShortCode
        const maxLen = 5;
        const base = resolvedValue.slice(0, Math.min(3, maxLen - 2));
        finalValue = `testData.uniqueShortCode('${base}', ${maxLen})`;
        isUniqueValue = true;
      } else if (fieldLower.includes('name') || fieldLower.includes('title') || fieldLower.includes('description')) {
        // Name/description fields: use uniqueName
        const base = resolvedValue.replace(/\s+/g, '').slice(0, 20) || 'Test';
        finalValue = `testData.uniqueName('${base}')`;
        isUniqueValue = true;
      } else {
        // Other string fields: keep the value but append unique suffix
        const base = resolvedValue.slice(0, 30);
        finalValue = `\`${base}_\${testData.uniqueName('').slice(1)}\``;
        isUniqueValue = true;
      }
    } else {
      finalValue = resolvedValue;
    }

    // Strategy-driven compilation: check for pageModel strategy metadata
    const strategyKind = (step as any).strategyKind || '';
    const framework = (step as any).framework || '';
    const preWaits: string[] = (step as any).preWaits || [];

    // Generate pre-wait code from strategy
    const preWaitCode = preWaits.length > 0
      ? preWaits.map((w: string) => `    // Strategy wait: ${w}\n    await waitForAngular(page);`).join('\n')
      : '';

    // Rich text editor strategy (TinyMCE / CKEditor)
    if (strategyKind === 'edit-rich-text' || framework === 'tinymce' || framework === 'ckeditor') {
      return this.compileRichTextFill(selector, finalValue, step.field, framework);
    }

    // Kendo-specific fill strategy
    if (framework === 'kendo-ui' || (step as any).isKendo) {
      const valueExpr = isUniqueValue ? finalValue : `'${escapeForSingleQuote(finalValue)}'`;
      return `
    // Fill ${step.field} with value: ${finalValue} [Kendo UI strategy]
    console.log('Filling ${escapeForDoubleQuote(step.field)} [Kendo]');
${preWaitCode ? preWaitCode + '\n' : ''}    await waitForAngular(page);
    await waitForLoadingMask(page);
    await universalFill(page, '${escapeForSingleQuote(selector)}', ${valueExpr}, { isKendo: true, slowTyping: true });
    await kendoStabilizationDelay(page);`;
    }

    // Angular form control strategy
    if (framework === 'angular') {
      const valueExpr = isUniqueValue ? finalValue : `'${escapeForSingleQuote(finalValue)}'`;
      return `
    // Fill ${step.field} with value: ${finalValue} [Angular strategy]
    console.log('Filling ${escapeForDoubleQuote(step.field)} [Angular]');
${preWaitCode ? preWaitCode + '\n' : ''}    await waitForAngular(page);
    await waitForLoadingMask(page);
    await universalFill(page, '${escapeForSingleQuote(selector)}', ${valueExpr}, { isKendo: false, slowTyping: true });
    // Wait for Angular change detection to stabilize
    await page.waitForTimeout(500);
    await waitForAngular(page);`;
    }

    // Generic fill
    const isKendo = (step as any).isKendo || false;
    const confidence = (step as any).confidence !== undefined ? ` (confidence: ${((step as any).confidence * 100).toFixed(0)}%)` : '';
    const alternatives = (step as any).selectorAlternatives?.length > 0 ? ` [Alternatives: ${(step as any).selectorAlternatives.join(', ')}]` : '';

    const valueExpr = isUniqueValue ? finalValue : `'${escapeForSingleQuote(finalValue)}'`;
    return `
    // Fill ${step.field} with value: ${finalValue}${confidence}${alternatives}
    console.log('Filling ${escapeForDoubleQuote(step.field)}');
${preWaitCode ? preWaitCode + '\n' : ''}    await waitForAngular(page);
    await waitForLoadingMask(page);
    await universalFill(page, '${escapeForSingleQuote(selector)}', ${valueExpr}, { isKendo: ${isKendo}, slowTyping: true });`;
  }

  /**
   * Compile a fill for a rich text editor (TinyMCE / CKEditor)
   */
  private compileRichTextFill(selector: string, value: string, fieldName: string, framework: string): string {
    if (framework === 'tinymce' || selector.toLowerCase().includes('tox') || selector.toLowerCase().includes('mce-')) {
      return `
    // Fill rich text editor ${fieldName} [TinyMCE strategy]
    console.log('Setting TinyMCE content: ${escapeForDoubleQuote(fieldName)}');
    await waitForAngular(page);
    await waitForLoadingMask(page);
    // TinyMCE: set content through editor API via iframe
    const editorFrame = page.frameLocator('iframe.tox-edit-area__iframe').first();
    await editorFrame.locator('body#tinymce').click();
    await editorFrame.locator('body#tinymce').fill('${escapeForSingleQuote(value)}');
    await page.waitForTimeout(500);`;
    }

    // CKEditor fallback
    return `
    // Fill rich text editor ${fieldName} [CKEditor strategy]
    console.log('Setting CKEditor content: ${escapeForDoubleQuote(fieldName)}');
    await waitForAngular(page);
    await waitForLoadingMask(page);
    // CKEditor: find editable content root and set text
    const ckContent = page.locator('${escapeForSingleQuote(selector)}').locator('.ck-content, [contenteditable="true"]').first();
    await ckContent.click();
    await ckContent.fill('${escapeForSingleQuote(value)}');
    await page.waitForTimeout(500);`;
  }

  private compileClickStep(step: ClickStep): string {
    const elementName = step.element || 'Unknown';

    // PRIORITY 1: Look up real selector from discovery cache
    let resolvedSelectorHint = step.selectorHint;
    let locatorSource = 'step.selectorHint';
    if (!resolvedSelectorHint && this.options.moduleName) {
      const discovered = DiscoveryCacheService.lookupElementDefinition(elementName, this.options.moduleName);
      if (discovered) {
        resolvedSelectorHint = discovered.selector;
        locatorSource = 'DiscoveryCache';
        (step as any).framework = (step as any).framework || discovered.framework;
        (step as any).strategyKind = (step as any).strategyKind || discovered.strategyKind;
      }
    }

    // PRIORITY 1.5: Look up from locator knowledge base (successful test runs)
    if (!resolvedSelectorHint && this.options.moduleName) {
      const knownLocator = SkillRegistryService.findBestLocator(elementName, 'click');
      if (knownLocator && knownLocator.confidence >= 0.7) {
        resolvedSelectorHint = knownLocator.selector;
        locatorSource = `SkillRegistry(confidence=${(knownLocator.confidence * 100).toFixed(0)}%)`;
        (step as any).framework = (step as any).framework || knownLocator.framework;
        (step as any).strategyKind = (step as any).strategyKind || knownLocator.strategyKind;
      }
    }

    if (resolvedSelectorHint && hasTemplateVariables(resolvedSelectorHint)) {
      resolvedSelectorHint = resolveTemplate(resolvedSelectorHint, buildDefaultContext());
      const unresolved = getUnresolvedVariables(resolvedSelectorHint);
      if (unresolved.length > 0) {
        console.warn(`[JSONToPlaywrightCompiler] Unresolved variables in selectorHint for ${elementName}: ${unresolved.join(', ')}. Using text-based selector.`);
        resolvedSelectorHint = '';
      }
    }
    const strategyKind = (step as any).strategyKind || '';
    const preWaits: string[] = (step as any).preWaits || [];
    const preWaitCode = preWaits.length > 0
      ? preWaits.map((w: string) => `    // Strategy wait: ${w}\n    await waitForAngular(page);`).join('\n')
      : '';
    if (strategyKind === 'modal-action') {
      const sel = resolvedSelectorHint || '.k-dialog, [role="dialog"], .modal';
      return `
    // Modal action: ${escapeForDoubleQuote(elementName)} [Modal strategy]
    console.log('Modal action: ${escapeForDoubleQuote(elementName)}');
${preWaitCode ? preWaitCode + '\n' : ''}    await waitForAngular(page);
    await page.locator('.k-dialog, [role="dialog"], .modal').waitFor({ state: 'visible', timeout: 10000 }).catch(() => {});
    await page.waitForTimeout(300);
    await healedClick(page, '${escapeForSingleQuote(sel)}', { timeout: 30000 });`;
    }
    if (strategyKind === 'grid-action') {
      const sel = resolvedSelectorHint || '.k-grid';
      return `
    // Grid action: ${escapeForDoubleQuote(elementName)} [Grid strategy]
    console.log('Grid action: ${escapeForDoubleQuote(elementName)}');
${preWaitCode ? preWaitCode + '\n' : ''}    await waitForAngular(page);
    await waitForLoadingMask(page);
    await page.locator('${escapeForSingleQuote(sel)} tbody > tr').first().waitFor({ state: 'visible', timeout: 15000 }).catch(() => {});
    await healedClick(page, '${escapeForSingleQuote(sel)}', { timeout: 30000 });`;
    }
    if (strategyKind === 'navigate-tab') {
      const sel = resolvedSelectorHint || '.k-tabstrip .k-link';
      return `
    // Tab navigation: ${escapeForDoubleQuote(elementName)} [Tab strategy]
    console.log('Tab navigation: ${escapeForDoubleQuote(elementName)}');
${preWaitCode ? preWaitCode + '\n' : ''}    await waitForAngular(page);
    await healedClick(page, '${escapeForSingleQuote(sel)}', { timeout: 30000 });
    await page.waitForTimeout(500);
    await waitForAngular(page);`;
    }
    if (resolvedSelectorHint && resolvedSelectorHint.trim()) {
      const confidence = (step as any).confidence !== undefined ? ` (confidence: ${((step as any).confidence * 100).toFixed(0)}%)` : '';
      const alternatives = (step as any).selectorAlternatives?.length > 0 ? ` [Alternatives: ${(step as any).selectorAlternatives.join(', ')}]` : '';
      return `
    // Click ${escapeForDoubleQuote(elementName)}${confidence}${alternatives}
    console.log('Clicking: ${escapeForDoubleQuote(elementName)}');
${preWaitCode ? preWaitCode + '\n' : ''}    await waitForAngular(page);
    await waitForLoadingMask(page);
    await healedClick(page, '${escapeForSingleQuote(resolvedSelectorHint)}', { timeout: 30000 });`;
    }
    const buttonText = elementName.replace(/button/gi, '').replace(/click/gi, '').trim();
    if (buttonText) {
      // FIX I-001: Icon-only buttons have no text, so has-text() always fails.
      // Generate a multi-strategy selector chain that tries title, aria-label,
      // Kendo icon classes, and class patterns before falling back to text.
      const robustSelector = SelectorValidatorService.buildButtonSelectorChain(buttonText);
      return `
    // Click ${escapeForDoubleQuote(elementName)} [icon-aware multi-strategy selector]
    console.log('Clicking: ${escapeForDoubleQuote(elementName)}');
${preWaitCode ? preWaitCode + '\n' : ''}    await waitForAngular(page);
    await waitForLoadingMask(page);
    await healedClick(page, '${escapeForSingleQuote(robustSelector)}', { timeout: 30000 });`;
    }
    const selector = this.getSelectorForElement(elementName);
    return `
    // Click ${escapeForDoubleQuote(elementName)}
    console.log('Clicking: ${escapeForDoubleQuote(elementName)}');
${preWaitCode ? preWaitCode + '\n' : ''}    await waitForAngular(page);
    await waitForLoadingMask(page);
    await healedClick(page, '${escapeForSingleQuote(selector)}', { timeout: 30000 });`;
  }

  private compileWaitForSelectorStep(step: WaitForSelectorStep): string {
    const state = step.state || 'visible';
    const timeout = step.timeout || 15000;
    // Skip redundant loading mask waits on initial page load — no mask exists yet
    const waitTarget = step.selector === '.k-loading-mask' && state === 'hidden'
      ? ''
      : `
    // Wait for selector: ${escapeForDoubleQuote(step.selector)} (state: ${state})
    console.log('Waiting for: ${escapeForDoubleQuote(step.selector)}');
    await page.locator('${escapeForSingleQuote(step.selector)}').waitFor({ state: '${state}', timeout: ${timeout} });`;
    return waitTarget;
  }

  private compileWaitForResponseStep(step: WaitForResponseStep): string {
    const status = step.status || 200;
    const timeout = step.timeout || 30000;

    // FIX P0: Convert pipe-separated patterns to proper regex
    // String.includes() does NOT support regex - it looks for literal string
    const isRegexPattern = step.urlPattern.includes('|') || step.urlPattern.includes('.*');

    if (isRegexPattern) {
      const regexPattern = step.urlPattern
        .replace(/\//g, '\\/')
        .replace(/\.\*/g, '.*');
      return `
    // Wait for API response: ${escapeForDoubleQuote(step.urlPattern)}
    console.log('Waiting for response: ${escapeForDoubleQuote(step.urlPattern)}');
    await page.waitForResponse(
      response => response.url().match(new RegExp('${escapeForSingleQuote(regexPattern)}')) && response.status() === ${status},
      { timeout: ${timeout} }
    );`;
    }

    return `
    // Wait for API response: ${escapeForDoubleQuote(step.urlPattern)}
    console.log('Waiting for response: ${escapeForDoubleQuote(step.urlPattern)}');
    await page.waitForResponse(
      response => response.url().includes('${escapeForSingleQuote(step.urlPattern)}') && response.status() === ${status},
      { timeout: ${timeout} }
    );`;
  }

  private compileSelectOptionStep(step: SelectOptionStep): string {
    const selector = step.selectorHint || this.getSelectorForField(step.field);
    const strategyKind = (step as any).strategyKind || '';
    const framework = (step as any).framework || '';
    const preWaits: string[] = (step as any).preWaits || [];
    const preWaitCode = preWaits.length > 0
      ? preWaits.map((w: string) => `    // Strategy wait: ${w}\n    await waitForAngular(page);`).join('\n')
      : '';

    // Kendo UI dropdown strategy: open detached popup, then select from overlay
    if (framework === 'kendo-ui' || strategyKind === 'select') {
      return `
    // Select '${escapeForDoubleQuote(step.value)}' from ${escapeForDoubleQuote(step.field)} [Kendo dropdown strategy]
    console.log('Selecting option: ${escapeForDoubleQuote(step.value)}');
${preWaitCode ? preWaitCode + '\n' : ''}    await waitForAngular(page);
    await waitForLoadingMask(page);
    // Kendo dropdown: click trigger to open detached popup, then select from overlay
    await page.locator('${escapeForSingleQuote(selector)}').click();
    await page.waitForTimeout(300);
    // Kendo options are often detached under body in .k-list or .k-popup
    const optionLoc = page.locator('.k-popup .k-list-item, .k-list .k-list-item, [role="option"]').filter({ hasText: '${escapeForSingleQuote(step.value)}' }).first();
    await optionLoc.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {});
    await optionLoc.click();
    await kendoStabilizationDelay(page);`;
    }

    return `
    // Select '${escapeForDoubleQuote(step.value)}' from ${escapeForDoubleQuote(step.field)}
    console.log('Selecting option: ${escapeForDoubleQuote(step.value)}');
${preWaitCode ? preWaitCode + '\n' : ''}    await waitForAngular(page);
    await waitForLoadingMask(page);
    await page.locator('${escapeForSingleQuote(selector)}').selectOption('${escapeForSingleQuote(step.value)}');
    await kendoStabilizationDelay(page);`;
  }

  private compileCheckStep(step: CheckStep): string {
    const selector = step.selectorHint || this.getSelectorForField(step.field);
    const preWaits: string[] = (step as any).preWaits || [];
    const preWaitCode = preWaits.length > 0
      ? preWaits.map((w: string) => `    // Strategy wait: ${w}\n    await waitForAngular(page);`).join('\n')
      : '';

    return `
    // Check ${escapeForDoubleQuote(step.field)}
    console.log('Checking: ${escapeForDoubleQuote(step.field)}');
${preWaitCode ? preWaitCode + '\n' : ''}    await waitForAngular(page);
    await waitForLoadingMask(page);
    await page.locator('${escapeForSingleQuote(selector)}').check();
    await kendoStabilizationDelay(page);`;
  }

  private compileUploadFileStep(step: UploadFileStep): string {
    const selector = step.selectorHint || this.getSelectorForField(step.field);
    return `
    // Upload file: ${escapeForDoubleQuote(step.filePath)} to ${escapeForDoubleQuote(step.field)}
    console.log('Uploading file: ${escapeForDoubleQuote(step.filePath)}');
    await waitForAngular(page);
    await waitForLoadingMask(page);
    await page.locator('${escapeForSingleQuote(selector)}').setInputFiles('${escapeForSingleQuote(step.filePath)}');
    await kendoStabilizationDelay(page);`;
  }

  private compileHoverStep(step: HoverStep): string {
    return `
    // Hover over: ${escapeForDoubleQuote(step.selector)}
    console.log('Hovering: ${escapeForDoubleQuote(step.selector)}');
    await waitForAngular(page);
    await page.locator('${escapeForSingleQuote(step.selector)}').hover();
    await kendoStabilizationDelay(page);`;
  }

  private compileExecuteStep(step: ExecuteStep): string {
    const helperName = step.helper;
    const args = step.args || {};

    // Built-in helpers that are implemented as utility functions
    const knownHelpers: Record<string, (args: Record<string, any>) => string> = {
      'login': () => `
    // Helper: Login with stored credentials
    console.log('Executing login helper');
    await waitForAngular(page);
    const loginSuccess = await performLogin(page, {
      username: _credentials.username,
      password: _credentials.password,
      idNumber: _credentials.idNumber
    }, 120000);
    if (!loginSuccess) {
      throw new Error('Login failed with stored credentials');
    }`,

      'navigateTo': () => {
        const path = args.path || args.url || '/';
        return `
    // Helper: Navigate to ${path}
    console.log('Navigating to: ${path}');
    await waitForAngular(page);
    await page.goto('${path}', { waitUntil: 'networkidle' });`;
      },

      'waitForGridLoad': () => {
        const timeout = args.timeout || 15000;
        return `
    // Helper: Wait for Kendo grid to load data
    console.log('Waiting for grid to load...');
    await waitForAngular(page);
    await waitForLoadingMask(page);
    const grid = page.locator('.k-grid');
    await grid.waitFor({ state: 'visible', timeout: ${timeout} });
    const rowCount = await grid.locator('tbody > tr').count();
    if (rowCount === 0) {
      console.warn('Grid loaded with no data rows');
    } else {
      console.log(\`Grid loaded with \${rowCount} rows\`);
    }`;
      },

      'openGridRow': () => {
        const rowIndex = args.rowIndex || 0;
        const columnKey = args.column || 'name';
        return `
    // Helper: Open row ${rowIndex} in grid by ${columnKey}
    console.log('Opening grid row ${rowIndex}');
    await waitForAngular(page);
    const grid = page.locator('.k-grid');
    const row = grid.locator(\`tbody > tr:nth-child(\${${rowIndex} + 1})\`);
    await row.waitFor({ state: 'visible' });
    const editBtn = row.locator('.k-grid-edit, .btn-edit, [data-action="edit"]');
    await healedClick(page, editBtn);`;
      },

      'fillForm': () => {
        const fields = args.fields || {};
        const lines = Object.entries(fields).map(([field, value]) =>
          `    await waitForAngular(page);
    await page.locator('[data-testid="${field}"], [name="${field}"]').fill('${value}');`
        ).join('\n');
        return `
    // Helper: Fill form fields
console.log('Filling form with ${Object.keys(fields).length} fields');
${lines}`;
      },

      'clickButton': () => {
        const buttonText = args.text || args.buttonText || '';
        return `
    // Helper: Click button "${buttonText}"
    console.log('Clicking button: ${buttonText}');
    await waitForAngular(page);
    const btn = page.locator(\`button:has-text("${buttonText}")\`);
    await healedClick(page, btn);`;
      },

      'selectKendoDropdown': () => {
        const field = args.field || '';
        const value = args.value || '';
        return `
    // Helper: Select Kendo dropdown option
    console.log('Selecting "${value}" from ${field}');
    await waitForAngular(page);
    const dropdown = page.locator('[role="combobox"], select[name="${field}"], [data-testid="${field}"]');
    await dropdown.click();
    await page.locator(\`.k-list-item:has-text("${value}")\`).click();
    await kendoStabilizationDelay(page);`;
      },

      'scrollToElement': () => {
        const selector = args.selector || '';
        return `
    // Helper: Scroll to element ${selector}
    console.log('Scrolling to: ${selector}');
    await waitForAngular(page);
    const el = page.locator('${selector}');
    await el.scrollIntoViewIfNeeded();`;
      },

      'takeScreenshot': () => {
        const name = args.name || 'checkpoint';
        return `
    // Helper: Take screenshot "${name}"
    console.log('Taking screenshot: ${name}');
    await page.screenshot({ path: 'test-results/screenshots/${name}.png', fullPage: true });`;
      },

      'verifyUrlContains': () => {
        const expected = args.expected || '';
        return `
    // Helper: Verify URL contains "${expected}"
    console.log('Verifying URL contains: ${expected}');
    await expect(page).toHaveURL(new RegExp('${expected}'));`;
      },

      // Additional helpers for common GlobalHR patterns
      'waitForGridData': () => {
        const timeout = args.timeout || 15000;
        return `
    // Helper: Wait for grid to have data rows (not just loading)
    console.log('Waiting for grid data...');
    await waitForAngular(page);
    await waitForLoadingMask(page);
    const gridCheck = page.locator('.k-grid tbody > tr');
    await gridCheck.first().waitFor({ state: 'visible', timeout: ${timeout} });
    const rowCount = await gridCheck.count();
    console.log(\`Grid has \${rowCount} data rows\`);`;
      },

      'clickGridRow': () => {
        const rowIndex = args.rowIndex ?? 0;
        const column = args.column || 0;
        return `
    // Helper: Click cell in grid row ${rowIndex}, column ${column}
    console.log('Clicking grid row ${rowIndex}');
    await waitForAngular(page);
    const row = page.locator(\`.k-grid tbody > tr:nth-child(\${${rowIndex} + 1})\`);
    await row.waitFor({ state: 'visible', timeout: 10000 });
    const cell = row.locator(\`td:nth-child(\${${column} + 1})\`);
    await healedClick(page, cell);`;
      },

      'closeModal': () => {
        return `
    // Helper: Close modal/dialog
    console.log('Closing modal...');
    const closeBtn = page.locator('.k-dialog-close, .modal-close, [aria-label="Close"], .k-window-action button[aria-label*="close"]');
    if (await closeBtn.isVisible({ timeout: 3000 }).catch(() => false)) {
      await healedClick(page, closeBtn);
    }
    await waitForAngular(page);`;
      },

      'confirmDialog': () => {
        const confirmText = args.confirmText || 'Yes';
        return `
    // Helper: Confirm dialog
    console.log('Confirming dialog...');
    const confirmBtn = page.locator(\`button:has-text("${confirmText}"), .k-dialog-buttongroup button:has-text("OK")\`);
    await healedClick(page, confirmBtn);
    await waitForAngular(page);`;
      },

      'dismissDialog': () => {
        return `
    // Helper: Dismiss/cancel dialog
    console.log('Dismissing dialog...');
    const cancelBtn = page.locator('button:has-text("Cancel"), button:has-text("No"), .k-dialog-buttongroup button:last-child');
    if (await cancelBtn.isVisible({ timeout: 3000 }).catch(() => false)) {
      await healedClick(page, cancelBtn);
    }`;
      },

      'selectDropdownByIndex': () => {
        const selector = args.selector || args.field || '';
        const index = args.index ?? 0;
        return `
    // Helper: Select dropdown option by index ${index}
    console.log('Selecting dropdown option ${index}');
    await waitForAngular(page);
    const dd = page.locator('${selector}');
    await healedClick(page, dd);
    await page.waitForTimeout(500);
    const option = page.locator(\`.k-list-item:nth-child(\${${index} + 1})\`);
    await healedClick(page, option);
    await kendoStabilizationDelay(page);`;
      },

      'clearField': () => {
        const selector = args.selector || args.field || '';
        return `
    // Helper: Clear field value
    console.log('Clearing field');
    await waitForAngular(page);
    const fld = page.locator('${selector}');
    await fld.click();
    await page.keyboard.press('Control+A');
    await page.keyboard.press('Backspace');
    await fld.dispatchEvent('change');`;
      },

      'dragAndDrop': () => {
        const fromSelector = args.from || args.source || '';
        const toSelector = args.to || args.target || '';
        return `
    // Helper: Drag and drop
    console.log('Dragging from "${fromSelector}" to "${toSelector}"');
    await waitForAngular(page);
    const source = page.locator('${fromSelector}');
    const target = page.locator('${toSelector}');
    await source.dragTo(target);`;
      },

      'switchTab': () => {
        const tabName = args.tab || args.tabName || '';
        return `
    // Helper: Switch to tab "${tabName}"
    console.log('Switching to tab: ${tabName}');
    await waitForAngular(page);
    const tab = page.locator(\`.k-tabstrip-items li:has-text("${tabName}"), [role="tab"]:has-text("${tabName}")\`);
    await healedClick(page, tab);
    await waitForAngular(page);`;
      },

      'expandAccordion': () => {
        const sectionName = args.section || args.name || '';
        return `
    // Helper: Expand accordion section "${sectionName}"
    console.log('Expanding accordion: ${sectionName}');
    await waitForAngular(page);
    const header = page.locator(\`.k-accordion-item [class*="header"]:has-text("${sectionName}"), .accordion-header:has-text("${sectionName}")\`);
    await healedClick(page, header);
    await waitForAngular(page);`;
      },
    };

    const generator = knownHelpers[helperName];
    if (generator) {
      return generator(args);
    }

    // Unknown helper — generate a page.evaluate() with a descriptive warning
    // instead of silently skipping with a // NOTE comment
    const argsJson = JSON.stringify(args).replace(/'/g, "\\'");
    return `
    // WARNING: Helper '${helperName}' is not natively implemented.
    // Generated page.evaluate() call — verify this works against the live DOM.
    // Args: ${argsJson}
    console.warn('[Helper] Unknown helper: ${helperName} — using generic evaluate');
    await page.evaluate((helperName, args) => {
      console.warn(\`[Custom Helper] \${helperName} called with: \${JSON.stringify(args)}\`);
      // TODO: Implement '${helperName}' in JSONToPlaywrightCompiler.compileExecuteStep()
    }, '${helperName}', ${argsJson});`;
  }

  /**
   * Compile a single assertion into Playwright code
   */
  private compileAssertion(assertion: AssertionStep): string {
    switch (assertion.type) {
      case 'assertText':
        return this.compileAssertText(assertion);
      case 'assertVisible':
        return this.compileAssertVisible(assertion);
      case 'assertUrl':
        return this.compileAssertUrl(assertion);
      case 'assertCount':
        return this.compileassertCount(assertion);
      case 'assertApiResponse':
        return this.compileAssertApiResponse(assertion);
      default:
        return `// Unknown assertion type: ${(assertion as any).type}`;
    }
  }

  private compileAssertText(assertion: AssertText): string {
    if (assertion.contains) {
      // FIX P0: Handle pipe-separated values as "any of these" patterns
      // toContainText('A|B|C') looks for literal "A|B|C" - not what we want
      const expectedValue = assertion.expected || '';
      const isPipeSeparated = expectedValue.includes('|');
      
      if (isPipeSeparated) {
        // Convert to regex for "match any of these" behavior
        const regexPattern = expectedValue
          .split('|')
          .map(part => part.trim())
          .filter(Boolean)
          .map(part => part.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'))
          .join('|');
        return `
    // Assert text contains any of: "${assertion.expected}"
    console.log('Verifying text contains any of: ${assertion.expected}');
    await expect(page.locator('${assertion.selector}')).toContainText(/${regexPattern}/i);`;
      }
      
      return `
    // Assert text contains: "${escapeForDoubleQuote(assertion.expected)}"
    console.log('Verifying text contains: ${escapeForDoubleQuote(assertion.expected)}');
    await expect(page.locator('${escapeForSingleQuote(assertion.selector)}')).toContainText('${escapeForSingleQuote(assertion.expected)}');`;
    }
    return `
    // Assert text equals: "${escapeForDoubleQuote(assertion.expected)}"
    console.log('Verifying text equals: ${escapeForDoubleQuote(assertion.expected)}');
    await expect(page.locator('${escapeForSingleQuote(assertion.selector)}')).toHaveText('${escapeForSingleQuote(assertion.expected)}');`;
  }

  private compileAssertVisible(assertion: AssertVisible): string {
    if (assertion.visible) {
      return `
    // Assert visible: ${escapeForDoubleQuote(assertion.selector)}
    console.log('Verifying visibility: ${escapeForDoubleQuote(assertion.selector)}');
    await expect(page.locator('${escapeForSingleQuote(assertion.selector)}')).toBeVisible();`;
    }
    return `
    // Assert hidden: ${escapeForDoubleQuote(assertion.selector)}
    console.log('Verifying hidden: ${escapeForDoubleQuote(assertion.selector)}');
    await expect(page.locator('${escapeForSingleQuote(assertion.selector)}')).toBeHidden();`;
  }

  private compileAssertUrl(assertion: AssertUrl): string {
    if (assertion.contains) {
      // Escape special regex characters in the expected URL
      const escapedUrl = assertion.expected.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      return `
    // Assert URL contains: ${escapeForDoubleQuote(assertion.expected)}
    console.log('Verifying URL contains: ${escapeForDoubleQuote(assertion.expected)}');
    await expect(page).toHaveURL(new RegExp('${escapeForSingleQuote(escapedUrl)}'));`;
    }
    return `
    // Assert URL equals: ${escapeForDoubleQuote(assertion.expected)}
    console.log('Verifying URL: ${escapeForDoubleQuote(assertion.expected)}');
    await expect(page).toHaveURL('${escapeForSingleQuote(assertion.expected)}');`;
  }

  private compileassertCount(assertion: AssertCount): string {
    return `
    // Assert count: ${assertion.expected} elements matching ${escapeForDoubleQuote(assertion.selector)}
    console.log('Verifying element count: ${assertion.expected}');
    const elements = page.locator('${escapeForSingleQuote(assertion.selector)}');
    await expect(elements).toHaveCount(${assertion.expected});`;
  }

  private compileAssertApiResponse(assertion: AssertApiResponse): string {
    const statusCheck = assertion.status ? `&& response.status() === ${assertion.status}` : '';
    const bodyCheck = assertion.bodyContains
      ? `&& (await response.text()).includes('${escapeForSingleQuote(assertion.bodyContains)}')`
      : '';
    
    // FIX P0: Convert pipe-separated patterns to proper regex (same as compileWaitForResponseStep)
    const isRegexPattern = assertion.urlPattern.includes('|') || assertion.urlPattern.includes('.*');
    
    if (isRegexPattern) {
      const regexPattern = assertion.urlPattern
        .replace(/\//g, '\\/')
        .replace(/\.\*/g, '.*');
      return `
    // Assert API response: ${escapeForDoubleQuote(assertion.urlPattern)}
    console.log('Verifying API response: ${escapeForDoubleQuote(assertion.urlPattern)}');
    await page.waitForResponse(
      response => response.url().match(new RegExp('${escapeForSingleQuote(regexPattern)}')) ${statusCheck} ${bodyCheck}
    );`;
    }
    
    return `
    // Assert API response: ${escapeForDoubleQuote(assertion.urlPattern)}
    console.log('Verifying API response: ${escapeForDoubleQuote(assertion.urlPattern)}');
    await page.waitForResponse(
      response => response.url().includes('${escapeForSingleQuote(assertion.urlPattern)}') ${statusCheck} ${bodyCheck}
    );`;
  }

  /**
   * Get selector for a business field name — uses enrichment pipeline
   * SelectorEnrichmentService + ElementRepositoryService + selectors file
   * are queried during spec generation; at compile time we have selectorHint.
   * This method generates plausible fallbacks when no enrichment was done.
   */
  private getSelectorForField(fieldName: string, selectorHint?: string): string {
    if (selectorHint && selectorHint.trim()) return selectorHint;

    const discoveredDefinition = DiscoveryCacheService.lookupElementDefinition(fieldName, this.options.moduleName);
    if (discoveredDefinition) {
      return discoveredDefinition.selector;
    }

    // Check discovery cache first
    const discovered = DiscoveryCacheService.lookupSelector(fieldName);
    if (discovered) {
      return discovered.selector;
    }

    const fieldClean = fieldName.toLowerCase().replace(/\s+/g, ' ');
    const fieldKey = fieldName.toLowerCase().replace(/\s+/g, '-');

    return `[data-testid="${fieldKey}"], label:has-text("${fieldClean}"):below + input, [name="${fieldKey}"], #${fieldKey}`;
  }

  /**
   * Get selector for a business element name (buttons, etc.)
   * Uses getByRole when possible, falls back to text-based locator.
   * Now checks discovery cache first for real selectors.
   */
  private getSelectorForElement(elementName: string, selectorHint?: string): string {
    if (selectorHint && selectorHint.trim()) return selectorHint;

    const discoveredDefinition = DiscoveryCacheService.lookupElementDefinition(elementName, this.options.moduleName);
    if (discoveredDefinition) {
      return discoveredDefinition.selector;
    }

    // Check discovery cache first
    const discovered = DiscoveryCacheService.lookupSelector(elementName);
    if (discovered) {
      return discovered.selector;
    }

    const elementLower = elementName.toLowerCase();
    // Normalize common button text
    const normalizedText = elementLower
        .replace(/\s*button\s*$/, '')
        .replace(/\s*add\s*(new)?\s*$/, 'Add New');

    return `button:has-text("${normalizedText}")`;
  }
}

/**
 * Quick compile function for convenience
 */
export function compileTestSpec(
  specification: TestSpecification,
  options: CompilerOptions
): string {
  const compiler = new JSONToPlaywrightCompiler(options);
  return compiler.compile(specification);
}

/**
 * Compile result with optional Page Object Model files
 */
export interface CompileResult {
  scriptContent: string;
  pageObjectFiles?: Array<{ className: string; fileName: string; content: string }>;
}

/**
 * Compile a test specification with optional Page Object Model generation.
 * Returns both the script content and generated POM files.
 */
export async function compileWithPageObjects(
  specification: TestSpecification,
  options: CompilerOptions
): Promise<CompileResult> {
  const compiler = new JSONToPlaywrightCompiler(options);
  const scriptContent = compiler.compile(specification);

  // Generate POM files alongside the script
  const { PageObjectGenerator } = await import('./PageObjectGenerator');

  // Convert spec scenarios to TestCase format for POM generation
  const testCases: any[] = specification.scenarios.map((scenario, idx) => {
    const steps: any[] = [
      ...scenario.steps.map((step: any, stepIdx: number) => ({
        stepNumber: stepIdx + 1,
        action: step.description || `${step.type}: ${JSON.stringify(step).substring(0, 80)}`,
        expectedResult: `Step ${stepIdx + 1} completed`,
      })),
      ...(scenario.assertions || []).map((assertion: any, assertIdx: number) => ({
        stepNumber: scenario.steps.length + assertIdx + 1,
        action: `Assert: ${assertion.type} on ${assertion.selector || assertion.urlPattern || 'element'}`,
        expectedResult: assertion.expected !== undefined ? String(assertion.expected) : 'Assertion passes',
      })),
    ];

    return {
      caseId: scenario.id || `TC-${idx + 1}`,
      title: scenario.name || `Scenario ${idx + 1}`,
      priority: (scenario.priority === 'high' ? 'High' : scenario.priority === 'low' ? 'Low' : 'Medium') as 'High' | 'Medium' | 'Low',
      steps,
      expectedOutcome: `All assertions pass for ${scenario.name}`,
      isEditable: true,
      tags: scenario.tags || [],
    };
  });

  const pomFiles = PageObjectGenerator.generateFromTestCases(testCases, specification.module);

  return {
    scriptContent,
    pageObjectFiles: pomFiles.map(p => ({ className: p.className, fileName: p.fileName, content: p.content })),
  };
}
