import * as fs from 'fs';
import * as path from 'path';

export class SkillRegistry {
    private static skillsCache: Record<string, string> = {};
    private static skillsDir = path.join(__dirname, '../skills');

    /**
     * Loads a skill prompt template from a JSON or MD file in the skills directory.
     */
    private static loadSkillTemplate(skillName: string): string {
        try {
            // Check cache first
            if (this.skillsCache[skillName]) return this.skillsCache[skillName];

            // Mapping for MD files (High Priority)
            const mdMapping: Record<string, string> = {
                "KENDO_SELECTOR_RULES": "KMT_Selector_Rules.md",
                "PLAYWRIGHT_STANDARDS": "Playwright_Standards.md",
                "GLOBALHR_CONTEXT": "GlobalHR_Context.md",
                "ISTQB_TESTING": "ISTQB_Testing_Knowledge.md",
                "GLOBALHR_USERGUIDE": "GlobalHR_UserGuide.md",
                "JIRA_BUG_PATTERNS": "Jira_Bug_Patterns.md",
                "GLOBALHR_INVESTIGATION": "GlobalHR/investigation-logic.md"
            };

            if (mdMapping[skillName]) {
                const mdPath = path.join(this.skillsDir, mdMapping[skillName]);
                if (fs.existsSync(mdPath)) {
                    const mdContent = fs.readFileSync(mdPath, 'utf8');
                    this.skillsCache[skillName] = mdContent;
                    return mdContent;
                }
            }

            // Auto-Generated Patterns (from Jira/Recordings)
            const autoGeneratedMapping: Record<string, string> = {
                "JIRA_GB340": "Auto-Generated/jira-patterns/GB-340.json",
                "RECORDING_LOGIN": "Auto-Generated/recording-patterns/login.json"
            };

            if (autoGeneratedMapping[skillName]) {
                const jsonPath = path.join(this.skillsDir, autoGeneratedMapping[skillName]);
                if (fs.existsSync(jsonPath)) {
                    const jsonContent = fs.readFileSync(jsonPath, 'utf8');
                    const data = JSON.parse(jsonContent);
                    // Convert to readable prompt format
                    let prompt = `## Pattern: ${skillName}\n\n`;
                    if (data.summary) prompt += `**Summary:** ${data.summary}\n\n`;
                    if (data.moduleName) prompt += `**Module:** ${data.moduleName}\n\n`;
                    if (data.checklist) {
                        prompt += `**Checklist:**\n`;
                        data.checklist.forEach((item: any) => {
                            prompt += `- [${item.category}] ${item.description}\n`;
                        });
                        prompt += `\n`;
                    }
                    if (data.learnedPatterns) {
                        prompt += `**Learned Patterns:**\n`;
                        data.learnedPatterns.forEach((pattern: string) => {
                            prompt += `- ${pattern}\n`;
                        });
                    }
                    this.skillsCache[skillName] = prompt;
                    return prompt;
                }
            }

            // Fallback to JSON files
            let filename = '';
            if (skillName === "KENDO_SELECTOR_RULES") filename = 'GlobalHR/navigation-patterns.json';
            else if (skillName === "PLAYWRIGHT_STANDARDS") filename = 'playwright.json';
            else if (skillName === "GLOBALHR_CONTEXT") filename = 'globalhr-context.json';
            else if (skillName === "USERLEVEL_RULES") filename = 'globalhr-userlevel.json';
            else if (skillName === "REPRODUCE_WORKFLOW") filename = 'globalhr-reproduce.json';
            else if (skillName === "MASTER_DATA_RULES") filename = 'master-data-rules.json';
            else if (skillName === "LEAVE_BUSINESS_RULES") filename = 'leave-business-rules.json';
            else if (skillName === "JIRA_TEST_CASES") filename = 'jira-test-cases.json';
            else if (skillName === "GENERIC_CRUD_FLOW") filename = 'GlobalHR/generic-crud-flow.json';
            else if (skillName === "NAVIGATION_PATTERNS") filename = 'GlobalHR/navigation-patterns.json';
            else return '';

            const filePath = path.join(this.skillsDir, filename);
            if (fs.existsSync(filePath)) {
                const content = fs.readFileSync(filePath, 'utf8');
                let template = '';
                try {
                    const data = JSON.parse(content);
                    template = data.template || JSON.stringify(data, null, 2);
                } catch {
                    template = content; // If not JSON, treat as raw string
                }
                this.skillsCache[skillName] = template;
                return template;
            }
        } catch (error) {
            console.error(`Error loading skill ${skillName}:`, error);
        }
        return '';
    }

    private static skills: Record<string, (params: any) => string> = {
        "ROOT_CAUSE_ANALYSIS": (params) => `
            Analyze the following error: ${params.error}
            In context of these steps: ${JSON.stringify(params.steps)}
            User Notes: ${JSON.stringify(params.annotations)}
            Provide a diagnostic verdict.
        `,
        "SELECTOR_REPAIR": (params) => `
            FORENSIC TASK: Repair a broken UI selector.
            
            Original Selector: ${params.oldSelector}
            Current DOM Context (Snippet): ${params.dom}
            
            INSTRUCTION:
            1. Find an element in the DOM snippet that matches the purpose of the original selector.
            2. Suggest a NEW, stable, and unique CSS selector.
            3. Return valid JSON only: { "bestSelector": "...", "confidence": 0.0-1.0, "reasoning": "..." }
        `,
        "KENDO_SELECTOR_RULES": (params) => {
            const template = SkillRegistry.loadSkillTemplate("KENDO_SELECTOR_RULES");
            if (template) return template;
            return `### DOM Selector Rules (Fallback)\nFocus on ng-reflect-name and formControlName.`;
        },
        "PLAYWRIGHT_STANDARDS": (params) => {
            const template = SkillRegistry.loadSkillTemplate("PLAYWRIGHT_STANDARDS");
            if (template) return template;
            return `### Playwright Standards (Fallback)\nUse test.step() and environment variables for URLs.`;
        },
        "GLOBALHR_CONTEXT": (params) => {
            const template = SkillRegistry.loadSkillTemplate("GLOBALHR_CONTEXT");
            if (template) return template;
            return `### GlobalHR Context (Fallback)\nGlobalHR Cloud uses Angular + Kendo UI. Use stable selectors.`;
        },
        "USERLEVEL_RULES": (params) => {
            const template = SkillRegistry.loadSkillTemplate("USERLEVEL_RULES");
            if (template) return template;
            return `### User Level Rules (Fallback)\nCheck Inactive, Allow Web Login, Restricted IP, Menu List, Employee List.`;
        },
        "REPRODUCE_WORKFLOW": (params) => {
            const template = SkillRegistry.loadSkillTemplate("REPRODUCE_WORKFLOW");
            if (template) return template;
            return `### Reproduce Workflow (Fallback)\nGenerate admin setup steps and test execution plan.`;
        },
        "ISTQB_TESTING": (params) => {
            const template = SkillRegistry.loadSkillTemplate("ISTQB_TESTING");
            if (template) return template;
            return `### ISTQB Testing Knowledge (Fallback)\nApply equivalence partitioning, boundary value analysis, and state transition testing.`;
        },
        "GLOBALHR_USERGUIDE": (params) => {
            const template = SkillRegistry.loadSkillTemplate("GLOBALHR_USERGUIDE");
            if (template) return template;
            return `### GlobalHR User Guide (Fallback)\nGlobalHR Cloud is multi-tenant Angular+Kendo. URL pattern: /{CUSTOMER_ID}/module.`;
        },
        "JIRA_BUG_PATTERNS": (params) => {
            const template = SkillRegistry.loadSkillTemplate("JIRA_BUG_PATTERNS");
            if (template) return template;
            return `### Jira Bug Patterns (Fallback)\nLeave module has highest defect density. Check balance calc, approval chain, and restriction bypass.`;
        },
        "MASTER_DATA_RULES": (params) => {
            const template = SkillRegistry.loadSkillTemplate("MASTER_DATA_RULES");
            if (template) return template;
            return `### Master Data Rules (Fallback)\n10 entities: Company, Department, Grade, Designation, Team, Label, Leave Type, Keyword, Public Holiday, GPS Location. Short code max 5 chars.`;
        },
        "LEAVE_BUSINESS_RULES": (params) => {
            const template = SkillRegistry.loadSkillTemplate("LEAVE_BUSINESS_RULES");
            if (template) return template;
            return `### Leave Business Rules (Fallback)\nLeave Policy: Max Day, Continuous Day, Monthly Rate, Carry Over, Off Day Deduction, Prerequisite Leave, Restriction Bridging.`;
        },
        "JIRA_TEST_CASES": (params) => {
            const template = SkillRegistry.loadSkillTemplate("JIRA_TEST_CASES");
            if (template) return template;
            return `### Jira Test Cases (Fallback)\n205 real test cases from QA team's Jira. Priority: OT (59), Leave (55), Attendance (45), Employee (19), Payroll (17).`;
        },
        "GENERIC_CRUD_FLOW": (params) => {
            const template = SkillRegistry.loadSkillTemplate("GENERIC_CRUD_FLOW");
            if (template) return template;
            return `### Generic CRUD Flow (Fallback)\n7 flows: Navigation, Create, Search, Edit, Delete, Export, Negative Testing. Reusable for any GlobalHR module.`;
        },
        "NAVIGATION_PATTERNS": (params) => {
            const template = SkillRegistry.loadSkillTemplate("NAVIGATION_PATTERNS");
            if (template) return template;
            return `### Navigation Patterns (Fallback)\nStable selectors for all GlobalHR UI components: buttons, dropdowns, datepickers, grids, modals, toasts. With failure recovery strategies.`;
        }
    };

    static executeSkill(skillName: string, params: any): string {
        const skill = this.skills[skillName];
        if (!skill) throw new Error(`Skill ${skillName} not found.`);
        return skill(params);
    }
}
