import { defineConfig, devices } from '@playwright/test';
import fs from 'fs';
import path from 'path';
import os from 'os';
import * as dotenv from 'dotenv';

// Load .env at the very beginning
dotenv.config();

/**
 * Cross-platform Chromium path detection.
 *
 * WHY: Playwright's browser installation paths differ between OSs.
 * - Windows: %LOCALAPPDATA%\ms-playwright\chromium-{revision}\chrome-win\chrome.exe
 * - Linux:   ${HOME}/.cache/ms-playwright/chromium-{revision}/chrome-linux/
 * - macOS:   ~/Library/Caches/ms-playwright/
 *
 * On Linux CI/VM, Playwright ships with its own Chromium binary — we don't need to
 * set executablePath at all. Playwright will auto-discover its bundled browser.
 *
 * On Windows, we may still need explicit paths when usernames contain spaces.
 */
function getChromiumPath(): string | undefined {
    // On Linux/macOS, let Playwright use its bundled Chromium.
    // No need to override executablePath — avoids breaking on different distro layouts.
    if (process.platform !== 'win32') return undefined;

    // Windows: try LOCALAPPDATA (standard) then USERPROFILE (fallback)
    const winRoot = process.env.LOCALAPPDATA || process.env.USERPROFILE;
    if (!winRoot) return undefined;

    // Try the standard Windows path
    const standardPath = path.join(winRoot, 'ms-playwright', 'chromium-1217', 'chrome-win', 'chrome.exe');
    if (fs.existsSync(standardPath)) return standardPath;

    // Try headless shell
    const headlessShellPath = path.join(winRoot, 'ms-playwright', 'chromium_headless_shell-1217', 'chrome-headless-shell-win64', 'chrome-headless-shell.exe');
    if (fs.existsSync(headlessShellPath)) return headlessShellPath;

    // Try to find any chromium installation under ms-playwright
    const msPlaywrightDir = path.join(winRoot, 'ms-playwright');
    if (fs.existsSync(msPlaywrightDir)) {
        const dirs = fs.readdirSync(msPlaywrightDir, { withFileTypes: true });
        for (const entry of dirs) {
            if (entry.isDirectory() && entry.name.startsWith('chromium-')) {
                const chromePath = path.join(msPlaywrightDir, entry.name, 'chrome-win', 'chrome.exe');
                if (fs.existsSync(chromePath)) return chromePath;
            }
            if (entry.isDirectory() && entry.name.startsWith('chromium_headless_shell-')) {
                const shellPath = path.join(msPlaywrightDir, entry.name, 'chrome-headless-shell-win64', 'chrome-headless-shell.exe');
                if (fs.existsSync(shellPath)) return shellPath;
            }
        }
    }

    return undefined;
}

/**
 * Dynamic DNS Resolution for Playwright
 * Reads cached DNS overrides generated by DnsResolverService.
 * Only applies host-rules if valid, non-stale cache entries exist.
 */
function getDynamicHostRules(): string[] {
    try {
        const cachePath = path.join(process.cwd(), 'local_storage', 'cache', 'dns-overrides.json');
        if (!fs.existsSync(cachePath)) return [];
        
        const overrides = JSON.parse(fs.readFileSync(cachePath, 'utf8'));
        if (!Array.isArray(overrides) || overrides.length === 0) return [];
        
        // Filter out stale entries based on TTL
        const validOverrides = overrides.filter((o: any) => {
            const age = Date.now() - new Date(o.resolvedAt).getTime();
            return age < (o.ttlMs || 600000); // Default 10 min TTL
        });
        
        if (validOverrides.length === 0) return [];
        
        // Use exact domain mapping (not wildcard) to avoid conflicts
        const rules = validOverrides.map((o: any) => `MAP ${o.domain} ${o.ip}`).join(', ');
        return [`--host-rules=${rules}`];
    } catch {
        return [];
    }
}

/**
 * Playwright Config for Go-Hybrid Forensic System
 * Supports dynamic environment variables for multi-site testing.
 * Auto-records video always, screenshots on failure only.
 */
export default defineConfig({
    // testDir: './tests/playwright', // Commented out to allow dynamic paths
    testIgnore: ['./api/**', './node_modules/**'],
    timeout: 120000, // Increased for slow network conditions (Myanmar internet)

    use: {
        // Dynamic Base URL
        baseURL: process.env.BASE_URL || 'https://test.globalhr.com.mm/ook',

        // OS-aware headless mode:
        // Linux VMs MUST run headless (no display server).
        // Windows local dev can run headful for debugging when PW_DEBUG=1.
        headless: process.env.PW_DEBUG !== '1' || process.platform !== 'win32',

        // Chromium security bypass to allow module loading over direct IP
        launchOptions: {
            // On Linux: undefined → Playwright auto-discovers its bundled Chromium.
            // On Windows: explicit path needed because usernames may contain spaces.
            executablePath: getChromiumPath(),
            args: [
                '--disable-web-security',
                '--ignore-certificate-errors',
                '--disable-dev-shm-usage',          // CRITICAL for Linux Docker/VM (small /dev/shm)
                '--disable-accelerated-2d-canvas',
                '--no-first-run',
                '--no-zygote',                       // CRITICAL for Linux (prevents zombie processes)
                '--disable-gpu',                     // Linux VMs often lack GPU acceleration
                '--headless=new',                    // Modern headless mode (not legacy)
                '--disable-extensions',
                ...getDynamicHostRules(),
            ],
            // Increase timeout for slow machines
            timeout: 60000,
        },

        // Playwright Best Practices: Smart Locators
        // Prefer getByRole, getByLabel, getByPlaceholder over CSS/XPath
        testIdAttribute: 'data-testid',

        // Dynamic video recording based on case importance
        video: 'on',

        // Screenshots on EVERY failure, and optionally on success for verification cases
        screenshot: 'on',

        // Trace for debugging
        // P1 FIX: Changed from 'on' to 'retain-on-failure' to save disk space
        trace: 'retain-on-failure',

        // Browser Context Options
        viewport: { width: 1280, height: 720 },
        ignoreHTTPSErrors: true,

        // Actionability options - Extended for slow network
        actionTimeout: 60000,      // 60 seconds for actions (click, fill)
        navigationTimeout: 120000, // 120 seconds for navigation

    },
    
    projects: [
        {
            name: 'chromium',
            use: { ...devices['Desktop Chrome'] },
        }
    ],

    reporter: [
        ['html', { outputFolder: 'test-results/html-report', open: 'never' }],
        ['json', { outputFile: 'test-results/results.json' }],
        ['list']
    ],

    outputDir: 'test-results/output',

    // Retry failed tests twice for better resilience
    // Set to 0: selector issues are bugs, not flaky tests. Retries waste time.
    retries: 0,

    // Workers for parallel execution
    // Dynamically set based on environment: CI gets more workers, local dev gets fewer
    workers: process.env.CI ? 4 : (process.env.PARALLEL_WORKERS ? parseInt(process.env.PARALLEL_WORKERS) : 2),

    // Max failures before stopping (0 = unlimited)
    maxFailures: process.env.CI ? 10 : 0,

    // Shard tests across multiple machines (for CI)
    // shard: process.env.CI ? { total: parseInt(process.env.SHARD_TOTAL || '1'), current: parseInt(process.env.SHARD_INDEX || '1') } : undefined,
});
