/**
 * AgenticTestExecutor
 *
 * Hybrid execution engine that mimics how Gemini CLI / Claude CLI use MCP Playwright:
 *   snapshot → AI identifies element → get ref → execute action → observe result → repeat
 *
 * Two modes:
 *   AGENTIC  — AI drives the browser in real-time using the current page snapshot.
 *              Used when no saved steps exist or a step fails.
 *   REPLAY   — Replays saved steps from TestScriptStore (zero AI cost).
 *              Used when stable steps exist from a prior successful agentic run.
 *
 * After a successful agentic run, action sequences are saved back to TestScriptStore
 * so future executions skip AI and replay directly (hybrid pattern).
 *
 * Requires @playwright/mcp >= 0.0.70 for browser_generate_locator + browser_verify_*.
 */

import { PlaywrightMcpClient } from './PlaywrightMcpClient';
import { McpStep } from '../../types/mcp.types';
import { AiControllerService } from '../shared/AiControllerService';
import { appLogger } from '../../utils/logger';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface AgenticGoal {
  /** Human-readable goal, e.g. "Verify Category dropdown shows values from Label Setup" */
  description: string;
  /** Max steps before giving up (default: 15) */
  maxSteps?: number;
  /** Timeout per run in ms (default: 120_000) */
  timeoutMs?: number;
}

export interface AgenticStepRecord {
  action: string;           // MCP tool name
  element?: string;         // Natural language element description
  ref?: string;             // MCP ref used (s123)
  selector?: string;        // CSS selector generated by browser_generate_locator
  text?: string;            // Value typed / option selected
  url?: string;             // URL navigated to
  role?: string;            // Accessible role for verify tools
  accessibleName?: string;  // Accessible name for verify tools
  expectedText?: string;    // Text expected to be visible
  passed: boolean;
  message?: string;
}

export interface AgenticRunResult {
  passed: boolean;
  steps: AgenticStepRecord[];
  durationMs: number;
  errorMessage?: string;
  /** McpStep[] compatible with TestScriptStore — saved for replay on future runs */
  replaySteps?: McpStep[];
}

// ─── Main executor ────────────────────────────────────────────────────────────

export class AgenticTestExecutor {
  /**
   * Run a goal-based agentic test.
   *
   * The executor takes a snapshot, asks the AI what to do next,
   * executes the action, and repeats until the goal is achieved or maxSteps is reached.
   *
   * Successful action sequences are returned as `replaySteps` for TestScriptStore caching.
   */
  static async run(
    client: PlaywrightMcpClient,
    goal: AgenticGoal,
    context?: {
      ticketDescription?: string;
      moduleName?: string;
      credentials?: { username: string; password: string };
    },
  ): Promise<AgenticRunResult> {
    const maxSteps = goal.maxSteps ?? 15;
    const timeoutMs = goal.timeoutMs ?? 120_000;
    const startMs = Date.now();
    const steps: AgenticStepRecord[] = [];
    const replaySteps: McpStep[] = [];

    appLogger.info(`[AgenticExecutor] Starting: "${goal.description}"`);

    try {
      const deadline = startMs + timeoutMs;

      for (let i = 0; i < maxSteps; i++) {
        if (Date.now() > deadline) {
          return {
            passed: false,
            steps,
            durationMs: Date.now() - startMs,
            errorMessage: `Timeout after ${timeoutMs}ms (${i} steps executed)`,
            replaySteps,
          };
        }

        // 1. Take snapshot of current page state
        let snapshot: string;
        try {
          const snapResult = await client.snapshot();
          snapshot = snapResult.text;
        } catch (e) {
          return {
            passed: false, steps, durationMs: Date.now() - startMs,
            errorMessage: `Failed to take snapshot: ${(e as Error).message}`,
          };
        }

        // 2. Ask AI what to do next
        const aiDecision = await this.askAi(goal, snapshot, steps, context);

        if (!aiDecision) {
          return {
            passed: false, steps, durationMs: Date.now() - startMs,
            errorMessage: 'AI returned no decision',
          };
        }

        // 3. Check if AI signals goal is complete
        if (aiDecision.action === 'done') {
          appLogger.info(`[AgenticExecutor] Goal achieved after ${i + 1} steps`);
          steps.push({ action: 'done', passed: true, message: aiDecision.message });
          return { passed: true, steps, durationMs: Date.now() - startMs, replaySteps };
        }

        // 4. Execute the AI-decided action
        const stepRecord = await this.executeDecision(client, aiDecision, snapshot);
        steps.push(stepRecord);

        if (!stepRecord.passed) {
          appLogger.warn(`[AgenticExecutor] Step ${i + 1} failed: ${stepRecord.message}`);
          return {
            passed: false, steps, durationMs: Date.now() - startMs,
            errorMessage: stepRecord.message,
            replaySteps,
          };
        }

        // 5. If we have a stable locator, build a McpStep for replay cache
        const replayStep = this.toReplayStep(stepRecord);
        if (replayStep) replaySteps.push(replayStep);

        appLogger.info(`[AgenticExecutor] Step ${i + 1}/${maxSteps}: ${stepRecord.action} — ${stepRecord.message}`);

        // Small pause between steps (let Angular/React settle)
        await new Promise(r => setTimeout(r, 800));
      }

      return {
        passed: false, steps, durationMs: Date.now() - startMs,
        errorMessage: `Max steps (${maxSteps}) reached without completing goal`,
        replaySteps,
      };

    } catch (err: any) {
      return {
        passed: false, steps, durationMs: Date.now() - startMs,
        errorMessage: err.message,
      };
    }
  }

  // ─── AI Decision ─────────────────────────────────────────────────────────

  private static async askAi(
    goal: AgenticGoal,
    snapshot: string,
    previousSteps: AgenticStepRecord[],
    context?: { ticketDescription?: string; moduleName?: string; credentials?: { username: string; password: string } },
  ): Promise<AiDecision | null> {
    const stepHistory = previousSteps.length > 0
      ? previousSteps.map((s, i) =>
          `Step ${i + 1}: ${s.action}(${s.element || s.selector || s.url || ''}) → ${s.passed ? 'OK' : 'FAILED: ' + s.message}`
        ).join('\n')
      : 'No steps yet — this is the first action.';

    const prompt = `You are a Playwright test automation agent controlling a real browser via MCP tools.

GOAL: ${goal.description}
${context?.moduleName ? `MODULE: ${context.moduleName}` : ''}
${context?.ticketDescription ? `TICKET CONTEXT:\n${context.ticketDescription.slice(0, 500)}` : ''}
${context?.credentials ? `LOGIN CREDENTIALS: username="${context.credentials.username}", password="${context.credentials.password}"\nIf you detect a login page, use these credentials to login first.` : ''}

ENVIRONMENT:
- Base URL: ${process.env.APP_URL || 'https://test.globalhr.com.mm/ook'}
- Current URL: (see snapshot)

STEPS TAKEN SO FAR:
${stepHistory}

CURRENT PAGE SNAPSHOT (accessibility tree):
${snapshot.slice(0, 4000)}

AVAILABLE ACTIONS (respond with exactly one JSON object):
- Navigate:  { "action": "browser_navigate", "url": "..." }
- Click:     { "action": "browser_click", "element": "human-readable name", "ref": "sXXX from snapshot" }
- Type:      { "action": "browser_type", "element": "...", "ref": "sXXX", "text": "value to type" }
- Select:    { "action": "browser_select_option", "element": "...", "ref": "sXXX", "text": "option text" }
- Verify text visible: { "action": "browser_verify_text_visible", "expectedText": "..." }
- Verify element visible: { "action": "browser_verify_element_visible", "role": "...", "accessibleName": "..." }
- Wait:      { "action": "browser_wait_for", "text": "text to wait for" }
- Run code:  { "action": "browser_run_code", "code": "playwright code snippet" }
- Done:      { "action": "done", "message": "what was verified/achieved" }

RULES:
1. Use "ref" from snapshot (e.g. "s15") when referencing elements — DO NOT invent refs.
2. If you can't find the element in the snapshot, navigate to the correct page first using the Base URL.
3. If the goal is verified/achieved, return { "action": "done", "message": "..." }.
4. If goal cannot be achieved (real bug found), return { "action": "done", "message": "REAL_BUG: <description>" }.
5. Return ONLY the JSON object — no explanation, no markdown.

Respond now:`;

    try {
      const raw = await AiControllerService.generate('REASONING', prompt);
      return this.parseDecision(raw);
    } catch (e: any) {
      appLogger.warn(`[AgenticExecutor] AI decision failed: ${e.message}`);
      return null;
    }
  }

  private static parseDecision(raw: string): AiDecision | null {
    try {
      // Strip markdown code fences if present
      const cleaned = raw.replace(/```json?\s*/gi, '').replace(/```\s*/g, '').trim();
      const firstBrace = cleaned.indexOf('{');
      const lastBrace = cleaned.lastIndexOf('}');
      if (firstBrace < 0 || lastBrace < 0) return null;
      return JSON.parse(cleaned.slice(firstBrace, lastBrace + 1));
    } catch {
      return null;
    }
  }

  // ─── Action execution ─────────────────────────────────────────────────────

  private static async executeDecision(
    client: PlaywrightMcpClient,
    decision: AiDecision,
    snapshot: string,
  ): Promise<AgenticStepRecord> {
    const base: AgenticStepRecord = {
      action: decision.action,
      element: decision.element,
      ref: decision.ref,
      text: decision.text,
      url: decision.url,
      passed: false,
    };

    try {
      switch (decision.action) {
        case 'browser_navigate': {
          await client.navigate(decision.url!);
          await new Promise(r => setTimeout(r, 2000));
          return { ...base, passed: true, message: `Navigated to ${decision.url}` };
        }

        case 'browser_click': {
          // Prefer ref from snapshot; fall back to resolveNameToRef
          let ref = decision.ref;
          if (!ref && decision.element) {
            ref = await client.resolveNameToRef(decision.element) ?? undefined;
          }
          const target = ref || decision.element || '';
          await client.click(target);

          // Generate and cache CSS locator for replay
          let selector: string | null = null;
          if (ref) {
            selector = await client.generateLocator(ref);
          }

          return { ...base, ref, selector: selector ?? undefined, passed: true, message: `Clicked ${decision.element || ref}` };
        }

        case 'browser_type': {
          let ref = decision.ref;
          if (!ref && decision.element) {
            ref = await client.resolveNameToRef(decision.element) ?? undefined;
          }
          const target = ref || decision.element || '';
          await client.fill(target, decision.text ?? '');

          let selector: string | null = null;
          if (ref) selector = await client.generateLocator(ref);

          return { ...base, ref, selector: selector ?? undefined, passed: true, message: `Typed "${decision.text}" into ${decision.element || ref}` };
        }

        case 'browser_select_option': {
          let ref = decision.ref;
          if (!ref && decision.element) {
            ref = await client.resolveNameToRef(decision.element) ?? undefined;
          }
          const target = ref || decision.element || '';
          await client.selectOption(target, decision.text ?? '');

          let selector: string | null = null;
          if (ref) selector = await client.generateLocator(ref);

          return { ...base, ref, selector: selector ?? undefined, passed: true, message: `Selected "${decision.text}" in ${decision.element || ref}` };
        }

        case 'browser_verify_text_visible': {
          const visible = await client.verifyTextVisible(decision.expectedText ?? '');
          return {
            ...base,
            expectedText: decision.expectedText,
            passed: visible,
            message: visible
              ? `Text visible: "${decision.expectedText}"`
              : `Text NOT visible: "${decision.expectedText}"`,
          };
        }

        case 'browser_verify_element_visible': {
          const visible = await client.verifyElementVisible(decision.role ?? '', decision.accessibleName ?? '');
          return {
            ...base,
            role: decision.role,
            accessibleName: decision.accessibleName,
            passed: visible,
            message: visible
              ? `Element visible: ${decision.role} "${decision.accessibleName}"`
              : `Element NOT visible: ${decision.role} "${decision.accessibleName}"`,
          };
        }

        case 'browser_wait_for': {
          await client.waitForText(decision.text ?? '', 10000);
          return { ...base, passed: true, message: `Waited for text: "${decision.text}"` };
        }

        case 'browser_run_code': {
          const result = await client.runCode(decision.code ?? '');
          return { ...base, passed: true, message: `Code executed: ${result.slice(0, 200)}` };
        }

        default:
          return { ...base, passed: false, message: `Unknown action: ${decision.action}` };
      }
    } catch (e: any) {
      return { ...base, passed: false, message: e.message };
    }
  }

  // ─── Replay step builder ─────────────────────────────────────────────────

  /**
   * Convert an agentic step record to a McpStep that can be saved to TestScriptStore
   * and replayed without AI on future runs.
   *
   * Only emits a replay step when a stable CSS selector is available
   * (either from browser_generate_locator or a direct CSS selector target).
   */
  private static toReplayStep(record: AgenticStepRecord): McpStep | null {
    const target = record.selector || record.ref;
    if (!target && record.action !== 'browser_navigate' &&
        record.action !== 'browser_verify_text_visible' &&
        record.action !== 'browser_verify_element_visible') {
      return null;
    }

    switch (record.action) {
      case 'browser_navigate':
        return { action: 'browser_navigate', url: record.url! } as any;

      case 'browser_click':
        return { action: 'browser_click', element: record.element, ref: record.ref, selector: target } as any;

      case 'browser_type':
        return { action: 'browser_type', element: record.element, ref: record.ref, selector: target, text: record.text } as any;

      case 'browser_select_option':
        return { action: 'browser_select_option', element: record.element, ref: record.ref, selector: target, option: record.text } as any;

      case 'browser_verify_text_visible':
        return { action: 'browser_check_ui_state', element: record.expectedText, property: 'text', expected: record.expectedText } as any;

      case 'browser_verify_element_visible':
        return { action: 'browser_check_ui_state', element: record.accessibleName, property: 'visibility', expected: 'visible' } as any;

      default:
        return null;
    }
  }
}

// ─── Internal AI decision type ────────────────────────────────────────────────

interface AiDecision {
  action: string;
  url?: string;
  element?: string;
  ref?: string;
  text?: string;
  code?: string;
  role?: string;
  accessibleName?: string;
  expectedText?: string;
  message?: string;
}
