import { chromium, Page } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

// Run: npx ts-node backend/scripts/auto-config-generator.ts "ModuleName"

async function extractFormConfig(page: Page, moduleName: string) {
    console.log(`\n🔍 Scanning the active form for Module: ${moduleName}...`);

    // We execute a JS function inside the browser to scrape all form fields dynamically.
    const fields = await page.evaluate(() => {
        const results: any[] = [];
        const inputs = document.querySelectorAll('input:not([type="hidden"]), select, textarea, kendo-dropdownlist, kendo-datepicker, kendo-combobox');
        
        inputs.forEach((el: any) => {
            // Find labels
            const getLabel = (element: Element) => {
                const id = element.id;
                if (id) {
                    const label = document.querySelector(`label[for="${id}"]`);
                    if (label) return label.textContent?.trim().replace('*', '');
                }
                const closestParent = element.closest('.form-group, .row');
                if (closestParent) {
                    const label = closestParent.querySelector('label');
                    if (label) return label.textContent?.trim().replace('*', '');
                }
                return element.getAttribute('name') || element.getAttribute('formcontrolname') || 'Unknown';
            };

            const name = el.getAttribute('name') || el.getAttribute('formcontrolname') || el.id;
            if (!name) return; // skip if we can't identify it

            let type = 'text';
            if (el.tagName.toLowerCase() === 'kendo-dropdownlist') type = 'kendo-dropdown';
            else if (el.tagName.toLowerCase() === 'kendo-datepicker') type = 'date';
            else if (el.tagName.toLowerCase() === 'textarea') type = 'text';
            else if (el.tagName.toLowerCase() === 'input') {
                type = el.getAttribute('type') || 'text';
                if (type === 'checkbox') type = 'checkbox';
                if (type === 'radio') type = 'radio';
            }

            const required = el.hasAttribute('required') || 
                             el.classList.contains('ng-invalid') ||
                             (el.closest('.form-group') && el.closest('.form-group').innerHTML.includes('text-danger'));

            results.push({
                name: name,
                label: getLabel(el),
                type: type,
                selector: `${el.tagName.toLowerCase()}[name="${name}"], ${el.tagName.toLowerCase()}[formcontrolname="${name}"]`,
                required: !!required,
                testValuePrefix: "TEST_"
            });
        });
        return results;
    });

    console.log(`✅ Found ${fields.length} fields!`);

    const config = {
        module: moduleName,
        menuPath: ["Master", moduleName], // User can update this manually later
        selectors: {
            addButton: "button.btn.btn-primary:has-text('Add New')",
            saveButton: "button.btn.btn-success:has-text('Save')",
            grid: "kendo-grid"
        },
        fields: fields
    };

    const dirName = moduleName.toLowerCase().replace(/\s+/g, '-');
    const folderPath = path.join(process.cwd(), 'systems', 'global-hr', 'modules', dirName);
    const testFolderPath = path.join(folderPath, 'tests');

    if (!fs.existsSync(folderPath)) fs.mkdirSync(folderPath, { recursive: true });
    if (!fs.existsSync(testFolderPath)) fs.mkdirSync(testFolderPath, { recursive: true });

    // Write config.json
    fs.writeFileSync(path.join(folderPath, 'config.json'), JSON.stringify(config, null, 4));
    console.log(`📁 Saved: ${path.join(folderPath, 'config.json')}`);

    // Generate Universal Test Script
    const crudScript = `import { test } from '@playwright/test';
import { UniversalFormHandler } from '../../../../../core/src/form-engine/UniversalFormHandler';
import * as configData from '../config.json';
import { loginAndPrepare } from '../../../../../backend/tests/playwright/login-helper'; // Adjust logic

test.describe('${moduleName} Auto-Generated CRUD', () => {
    test('Create, Verify, Update, Delete', async ({ page }) => {
        // Log in
        await loginAndPrepare(page, { url: process.env.BASE_URL, username: process.env.TEST_USERNAME, password: process.env.TEST_PASSWORD });

        const handler = new UniversalFormHandler(page, configData as any);
        await handler.navigateToModule();

        // Fill dynamic fields generated by auto-config
        const testData: any = {};
        for(const field of configData.fields) {
            testData[field.name] = \`\${field.testValuePrefix || ''}\${Date.now()}\`;
        }

        await test.step('Create', async () => {
             await handler.create(testData);
        });
    });
});
`;
    fs.writeFileSync(path.join(testFolderPath, 'crud.spec.ts'), crudScript);
    console.log(`📁 Auto-Generated Test: ${path.join(testFolderPath, 'crud.spec.ts')}`);
    console.log(`\n🎉 Module "${moduleName}" completely bootstrapped!`);
}

(async () => {
    const moduleName = process.argv[2];
    if (!moduleName) {
        console.error("❌ Please provide a module name. e.g.: npx ts-node auto-config-generator.ts \"Department\"");
        process.exit(1);
    }

    console.log(`🚀 Booting Auto-Config Generator for "${moduleName}"...`);
    const browser = await chromium.launch({ headless: false }); // Headed mode
    const page = await browser.newPage();
    
    // Suggest URL or manual login
    console.log("➡️ PLEASE LOG IN MANUALLY AND NAVIGATE TO THE TARGET MENU (e.g. Master -> Department)");
    console.log("➡️ CLICK 'ADD NEW' TO OPEN THE MODAL SO THE FORM IS VISIBLE ON SCREEN.");
    console.log("⏲️ Waiting for 60 seconds... Once you open the modal, the script will scan the fields automatically.\n");

    // Wait until user finds the form (simple timeout for simplicity, or we can prompt)
    // Here we wait for a specific modal class, or wait a flat 30 seconds
    try {
        await page.waitForSelector('.modal.show, kendo-dialog, form', { state: 'visible', timeout: 60000 });
        console.log("✅ Form detected on screen! Starting extraction in 2 seconds...");
        await page.waitForTimeout(2000); // Give it time to fully render
        await extractFormConfig(page, moduleName);
    } catch (e) {
        console.error("❌ Form (Modal) was not found within 60 seconds. Exiting.");
    } finally {
        await browser.close();
        process.exit(0);
    }
})();
